name: Pull Request Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-email:
    runs-on: ubuntu-latest

    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECIPIENT_PASWD: ${{ secrets.RECIPIENT_PASWD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests

    - name: Run Flask app in the background
      run: |
        nohup python app.py &
        sleep 5  # wait for the server to start

    - name: Test client script
      run: |
        python client.py

    - name: Check environment variables
      run: |
        echo "SENDER_EMAIL: $SENDER_EMAIL"
        echo "RECIPIENT_PASWD: $RECIPIENT_PASWD"

    - name: Run email script if tests pass
      run: |
        python send_email.py
